
library(shiny)
library(shinydashboard)
library(ggplot2)
library(dplyr)
library(rio)
library(lubridate)

data <- import_list("STOREDATA.xlsx")
data_details <- data$DETAILS
data_orders <- data$ORDERS
data <- merge(data_orders,data_details,by="Order ID",all = TRUE)

#Add day and month column
data$month<- month(data$`Order Date`)
data$day <- mday(data$`Order Date`)
data$quarter <- substr(quarters(data$`Order Date`),2,2)

#Dashboard header carrying the title of the dashboard
header<- dashboardHeader(title = "STORE DATA")
sidebar<-dashboardSidebar(
  sidebarMenu(
    #menuItem("Overview",tabName = "dashboard",icon = icon("dashboard")),
    menuItem("Overview",tabName = "dashboard",icon = icon("dashboard")),
    menuItem("Products",tabName="products",icon = icon("send",lib='glyphicon')),
    menuItem("Customers",tabName="customers",icon = icon("user",lib='glyphicon'))
  )
)
#KPI boxes for UI for navigation bar1
frow1 <- fluidRow(
  valueBoxOutput("value1"),
  valueBoxOutput("value2"),
  valueBoxOutput("value3")
  
)
frow2 <- fluidRow(
  box(
    title="Quartely Profit",
    status = "primary",
    solidHeader = TRUE,
    collapsible = TRUE,
    plotOutput("quartely_profit",height = "300px")
  ),
  box(
    title = "Monthly profit",
    status = "primary",
    solidHeader = TRUE,
    collapsible = TRUE,
    plotOutput("monthlyprofit",height = "300px")
  )
)
frow3 <- fluidRow(
  box(
    title="Number of products sold monthly",
    status = "primary",
    solidHeader = TRUE,
    collapsible = TRUE,
    plotOutput("products_month",height = "300px")
  ),
  box(
    title = "Frequent Payment Methods",
    status = "primary",
    solidHeader = TRUE,
    collapsible = TRUE,
    plotOutput("payment",height = "300px")
  )
)

#KPI boxes for UI for navigation bar2
dash2 <- fluidRow(
   valueBoxOutput("value4"),
  valueBoxOutput("value5"),
  valueBoxOutput("value6"),
)

dash2b <- fluidRow(
  box(
    title="Profits generated by category",
    status="primary",
    solidHeader=TRUE,
    collapsible = TRUE,
    plotOutput("profitable_product_cat")
  ),
  box(
    title="Top 3 profitable products",
    status="primary",
    solidHeader=TRUE,
    collapsible = TRUE,
    plotOutput("profitable_product")
  )
)

dash2c <- fluidRow(
  box(
    title="Categories by quantities sold",
    status="primary",
    solidHeader=TRUE,
    collapsible = TRUE,
    plotOutput("quantity_product_cat")
  ),
  box(
    title="Least profitable products",
    status="primary",
    solidHeader=TRUE,
    collapsible = TRUE,
    plotOutput("least_profitable_product")
  )
)
#Add 3rd dashboard for customers
testing <-sidebarLayout(
  sidebarPanel(width=6,
        box(width = 12,
        title="Total Number of unique customers",
        status = "primary",
        solidHeader = TRUE,
        collapsible = TRUE,
        valueBoxOutput("cust_No")),
  
       box(width = 12,
         title="Top 5 paying customers",
         status = "primary",
         solidHeader = TRUE,
         collapsible = TRUE,
         plotOutput("customer",height = "300px")),
    
        box(width = 12,
        title="customers who bought the most product",
        status = "primary",
        solidHeader = TRUE,
        collapsible = TRUE,
        plotOutput("cust_prod",height = "300px"))
    
  ),
  mainPanel(width=6,
    h3("Customer Region"),
    img(src = "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/India-map-en.svg/658px-India-map-en.svg.png", width = "300px", height = "300px"),
    br(),
    br(),
    h4(HTML("<b>Regions with most sales</b>")),
    tableOutput("regions")
  )
)

#combine the two fluid rows to make the body
#body <- dashboardBody(frow1,frow2,frow3)
body <- dashboardBody(
  tabItems(
    tabItem("dashboard",
            frow1,frow2,frow3),
  tabItem("products",
          dash2,dash2b,dash2c),
  tabItem("customers",
          testing
          )
)
)
ui <- dashboardPage(title = "STORE DATA",header,sidebar,body,skin = "blue"

)

# Define server logic 
server <- function(input, output) {
  #data manipulation to derive values of the KPI boxes
  net_profit <- sum(data$Profit) #net profit
  total_quantity <- sum(data$Quantity)
  average_quantity <- mean(data$Quantity) #Average product bought per day
  
  #Kpi for product dashboard
  top_selling_cat <-data %>% group_by(Category) %>% summarise(quantity=sum(Quantity))%>% filter(quantity==max(quantity))
  highest_selling<- data %>% group_by(`Sub-Category`) %>% summarise(Quantity=sum(Quantity)) %>% filter (Quantity==max(Quantity))
  profitable_product<- data %>% group_by(`Sub-Category`) %>% summarise(profit=sum(Profit)) %>% filter(profit==max(profit))
  
  #creating value Box output
  output$value1 <- renderValueBox({
    valueBox(
      formatC(net_profit, format="d", big.mark=','),
      paste('Net Profit:',net_profit),
      icon = icon("usd",lib='glyphicon'),
      color = "purple"
      )
  })
  output$value2 <- renderValueBox({
    valueBox(
      formatC(total_quantity,format="d",big.mark = ','),
      "Total Quantity of products sold",
      icon = icon("stats",lib='glyphicon')
    )
  })
  output$value3 <- renderValueBox({
    valueBox(
      formatC(average_quantity,format = "d",big.mark = ','),
      "Average Number of products sold daily",
      paste('Top Product:',average_quantity),
      icon = icon("menu-hamburger",lib='glyphicon'),
      color = "yellow"  
    )
  })
  #creating the plotOutput content
  output$quartely_profit <- renderPlot({
    quartely_profit <- data %>% group_by(quarter) %>% summarise(profit=sum(Profit))
    
    ggplot(quartely_profit,aes(quarter,profit,fill=quarter))+
      geom_col()+
      xlab("Quarters in a Year")+
      ylab("Profit")
    
  })
   output$monthlyprofit <- renderPlot({
     profitable_month <- data %>% group_by(month) %>% summarise(total=sum(Profit))
     #monthly profit
     ggplot(profitable_month,aes(month,total))+
       geom_line()+
       scale_x_continuous(n.breaks = 12)+
       geom_text(aes(label = total),vjust=-0.5) +
       xlab("Month")+
       ylab("Profit")
   })
 #No of products sold monthly
   output$products_month <- renderPlot({
  data %>% group_by(month) %>% summarise(total=sum(Quantity)) %>%
     ggplot(aes(month,total,fill=total))+
       geom_col()+
       scale_x_continuous(n.breaks=12)+
       xlab("Month")+
       ylab("Totals")
   })
   
   #Frequent Payment Methods
   output$payment <- renderPlot({
    data %>% group_by(PaymentMode) %>% summarise(Amount=sum(Quantity)) %>% mutate(pct=round((Amount/sum(Amount)*100),2))%>%
     ggplot(aes(x="",y=pct,fill=PaymentMode))+
       geom_bar(stat = "identity",width = 1)+
       coord_polar(theta = "y",start = 0)+
       geom_text(aes(label=paste0(pct,"%")),position=position_stack(vjust = 0.5))+
       guides(fill=guide_legend(title = "Payment Mode"))
   })
   
   #Outputs for dashboard2
   output$value4 <- renderValueBox({
     test="sold"
     valueBox(
       value= h4(paste('Top Selling Category:',top_selling_cat$quantity,top_selling_cat$Category ,test)),
       color = "purple",
       tags$img(src = "https://www.pngitem.com/pimgs/m/330-3303997_shirt-png-transparent-image-folded-clothes-png-png.png", height = 100, width = "100%"))
      
   })
   output$value5 <- renderValueBox({
     test= " bought"
     valueBox(
       value= h4(paste('Top Selling item:',highest_selling$Quantity,highest_selling$`Sub-Category`,test)),
       tags$img(src = "https://www.pngkit.com/png/detail/852-8528940_indian-traditional-dancer-vector-attire-dress-folk-indian.png", height = 100, width = "100%"))
     
   })
   output$value6 <- renderValueBox({
     test="$ sold"
     valueBox(
       value= h4(paste('Most profitable Product:',profitable_product$`Sub-Category`,profitable_product$profit,"$ sold")),
       color = "orange",
       tags$img(src = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTe6bJslByWeV-WOMnaG0lEZc5l0LkV03VxR6mahWKCoY72hyvjCV6MM4bVAQu1lvlmEbg&usqp=CAU", height = 100, width = "100%"))
     
   })
   #profits generated by category
   output$profitable_product_cat <- renderPlot({
       data %>% group_by(Category) %>% summarise(profit=sum(Profit)) %>%
       ggplot(aes(Category,profit,fill=Category))+
         geom_col()+
       geom_text(aes(label=profit),vjust=-0.5)+
       ylab("Profit")
     })
   #Top 3 profitable products
   output$profitable_product <- renderPlot({
     data %>% group_by(`Sub-Category`) %>% summarise(profit=sum(Profit)) %>% arrange(desc(profit)) %>% head(3) %>%
       ggplot(aes(`Sub-Category`,profit,fill=profit))+
       geom_col()+
       geom_text(aes(label=profit),vjust=-0.5)+
       xlab("Product")+
       ylab("Profit")
   })
   #profits generated by category
   output$quantity_product_cat <- renderPlot({
     data %>% group_by(Category) %>% summarise(quantity=sum(Quantity)) %>%
       ggplot(aes(Category,quantity))+
       geom_col()+
       geom_text(aes(label=quantity),vjust=-0.5)+
       ylab("Quatity")
   })
   #least profitable
   output$least_profitable_product <- renderPlot({
     data %>% group_by(`Sub-Category`) %>% summarise(profit=sum(Profit)) %>% arrange(desc(profit)) %>% tail(3) %>%
       ggplot(aes(`Sub-Category`,profit,fill=`Sub-Category`))+
       geom_col()+
       geom_text(aes(label=profit))+
       coord_flip()+
       xlab("Product")+
       ylab("Profit")+
       guides(fill=guide_legend(title="Products"))
   })
   
   #3rd Dashboard
   #Total no of unique customers
   output$cust_No <-  renderValueBox({
     cust <- n_distinct(data$CustomerName) 
     valueBox(
       formatC(cust,format="d",big.mark = ','),
       "",
       icon = icon("stats",lib='glyphicon')
     )
     
   })
   #Top 5 paying customers
   output$customer <- renderPlot({
     data %>% group_by(CustomerName) %>% summarise(Amount=sum(Amount)) %>% arrange(desc(Amount)) %>%
       head(5) %>% ggplot(aes(CustomerName,Amount,fill=CustomerName))+
       geom_col()+
       geom_text(aes(label=Amount),vjust=-0.5)
     
   })
   #customers who bought the most product
   output$cust_prod <- renderPlot({
     data %>% group_by(CustomerName) %>% summarise(most=sum(Quantity)) %>% arrange(desc(most))%>%
       head(6) %>%
       ggplot(aes(CustomerName,most,fill=CustomerName))+
       geom_col(fill="#00abff")+
       geom_text(aes(label=most),vjust=-0.5)+
       ylab("Quantity")
     
   })
   #Table of regions with most sales
   output$regions <- renderTable({
     data %>% group_by(City) %>% summarise(Amount=sum(Quantity)) %>%
       mutate(percent=paste0(round((Amount/sum(Amount)*100),2),"%")) %>% 
       arrange(desc(Amount))%>% head(5) 
   })
  #render map
}

# Run the application 
shinyApp(ui = ui, server = server)
